language: c

sudo: true

cache:
  directories:
    - ~/.ghc
    - ~/.cabal

matrix:
  include:
    - env: CABALVER=2.4 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-2.4,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.4.3
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.4.3], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.6.1
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.1], sources: [hvr-ghc]}}

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y freeglut3-dev
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal new-update

script:
 - cabal new-build
 - cabal sdist # no new-sdist yet :(

